language: node_js

node_js: 14

cache: npm

git:
  depth: 8

# install: npm ci

before_script: npm run copy-env

script:
  - npm run build
  - npm test
  - npm run envjslint-ci

after_script:
  #- npm run envjs
  - ls -alh dist/
  - npm audit
  - npm outdated

# End.
